{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-group
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme}}
    alb.ingress.kubernetes.io/target-type: {{.Values.ingress.target}}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.sg }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthcheck.path }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.group }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificate }}
    alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=true
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.preserve_host_header.enabled=true
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.xff_header_processing.mode=preserve
    alb.ingress.kubernetes.io/actions.{{ .Values.appName }}: '{ "Type": "forward", "ForwardConfig": { "TargetGroups": [ { "Weight": 100, "ServiceName": "{{ .Values.appName }}", "ServicePort": "{{ .Values.service.port }}" } ] } }'
    alb.ingress.kubernetes.io/tags: Owner=santiago.hernandez@strike.sh,Environment={{ .Values.envShort }},Monitoring=Datadog,ContainsUserData=true,UserDataStored=false,Description=InternalALBGroup,Repo=helm-apps
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.appName }}.{{ .Values.envShort }}.{{ .Values.ingress.domain }}
  labels:
    app: {{ .Values.appName }}
spec:
  # defaultBackend:
  #   service:
  #     name: {{ .Values.appName }}
  #     port:
  #       number: {{ .Values.service.port }}
  rules:
  - host: {{ .Values.appName }}.{{ .Values.envShort }}.{{ .Values.ingress.domain }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.appName }}
              port:
                number: {{ .Values.service.port }}
{{- end }}
